# Generated by Django 4.1.3 on 2022-11-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категария'},
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='created',
            new_name='create_ad',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='text',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='Images', verbose_name='Изображения'),
            preserve_default=False,
        ),
    ]
