# Generated by Django 4.1.3 on 2022-11-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_rename_created_ads_create_ad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.URLField(blank=True, verbose_name='Изображения'),
        ),
    ]
