# Generated by Django 4.1.3 on 2022-12-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_ads_phone_alter_ads_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
