# Generated by Django 4.1.3 on 2022-12-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ads_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='image',
            field=models.URLField(blank=True, verbose_name='Изображения'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
