# Generated by Django 4.1.3 on 2022-12-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_ads_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Ссылки Изображения'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='ads_images', verbose_name='Изображения'),
        ),
    ]
