# Generated by Django 4.1.3 on 2022-12-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_image_image_alter_image_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads_images', verbose_name='Изображения'),
        ),
    ]
