# Generated by Django 4.1.3 on 2022-12-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_ads_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылки Изображения'),
        ),
    ]
