# Generated by Django 4.1.3 on 2022-12-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_ads_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
    ]
