# Generated by Django 4.1.3 on 2023-01-30 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_ads_image_url_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.ads', verbose_name='Обьявления'),
        ),
    ]
